handson/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  url(r'^', include('survey.urls')),
  #url(r'^tutorial/', include('tutorial.urls')),
  url(r'^admin/', admin.site.urls),
]

survey/urls.py
from django.conf.urls import url
from . import views


app_name = 'survey'
urlpatterns = [
  #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index_view, name='index'),
  url(r'edit/$', views.edit_view, name='edit'),
  url(r'^login/$', views.login_view, name='login'),
  url(r'^logout/$', views.logout_view, name='logout'),
]

survey/models.py
from django.conf import settings
from django.core.validators import validate_comma_separated_integer_list
from django.db import models


DIFFICULT_POINTS_CHOICES = (
  (0, '環境構築（Python、Djangoのインストール）'),
  (1, '環境構築（Djangoのセットアップ、プロジェクト作成）'),
  (2, '環境構築（Herokuのセットアップ、デプロイ）'),
  (3, '環境構築（Gitのセットアップ）'),
  (4, 'ログインページを作る'),
  (5, 'Django urls'),
  (6, 'Django views'),
  (7, 'HTMLテンプレート作成'),
  (8, 'データベース操作'),
  (9, 'CSSの設定'),
  (10, 'テンプレートの拡張'),
  (11, 'アプリケーションの拡張'),
  (12, 'フォームの作成'),
  (13, 'その他'),
)

choices = {}
choices['time_settings'] = (
  ('too long', '長すぎる'), ('long', '長い'), ('just right', 'ちょうど良い'), ('short', '短い'), ('too short', '短すぎる'),
)
choices['handson_level'] = (
  ('too difficult', '難しすぎる'), ('difficult', '難しい'), ('understand', '理解できた'), ('easy', '易しい'), ('too easy', '易しすぎる'),
)
choices['handson_interest'] = (
  ('overall', '全体的に知りたい内容を含んでいた'), ('some', '一部知りたい内容を含んでいた'), ('thin', '興味関心が薄い分野だった'),
)
choices['handson_quantity'] = (
  ('too many', '項目が多すぎる'), ('many', '項目が多い'), ('just right', 'ちょうど良い'), ('short', '項目が少ない'), ('too short', '項目が少なすぎる'),
)

class Questionnaire(models.Model):
  user = models.OneToOneField(settings.AUTH_USER_MODEL, models.CASCADE)
  how_about_handson = models.TextField(default='', blank=True)
  difficult_points = models.CharField(max_length=128, blank=True,
                                      validators=[validate_comma_separated_integer_list])
  difficult_other = models.TextField(default='', blank=True)
  time_settings = models.CharField(max_length=16, choices=choices['time_settings'])
  handson_level = models.CharField(max_length=16, choices=choices['handson_level'])
  handson_interest = models.CharField(max_length=8, choices=choices['handson_interest'])
  handson_quantity = models.CharField(max_length=16, choices=choices['handson_quantity'])
  free_opinions = models.TextField(default='', blank=True)
  interest_trainings = models.TextField(default='', blank=True)

  def __str__(self):
    return str(self.user)

survey/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError
from django.utils.translation import ugettext as _
from .models import Questionnaire, DIFFICULT_POINTS_CHOICES


# Refered from: https://gist.github.com/romulocollopy/bffe38fa72af5bc427e1
class CommaSeparatedSelectInteger(forms.MultipleChoiceField):
    def to_python(self, value):
        if not value:
            return ''
        elif not isinstance(value, (list, tuple)):
            raise ValidationError(
                self.error_messages['invalid_list'], code='invalid_list'
            )
        l = []
        for val in value:
          try:
            n = int(val)
          except ValueError:
            continue
          l.append(val)
        return ','.join([str(val) for val in l])

    def validate(self, value):
        """
        Validates that the input is a string of integers separeted by comma.
        """
        if self.required and not value:
            raise ValidationError(
                self.error_messages['required'], code='required'
            )

        # Validate that each value in the value list is in self.choices.
        for val in value.split(','):
            if not self.valid_value(val):
                raise ValidationError(
                    self.error_messages['invalid_choice'],
                    code='invalid_choice',
                    params={'value': val},
                )

    def prepare_value(self, value):
        """ Convert the string of comma separated integers in list"""
        if not value:
          return ''
        #return value.split(',')
        return ','.join([str(val) for val in value])

      
class QuestionnaireForm(forms.ModelForm):

  difficult_points = CommaSeparatedSelectInteger(
    choices=[('', '無回答')] + [(i[0], i[1]) for i in DIFFICULT_POINTS_CHOICES],
    widget=forms.CheckboxSelectMultiple(),
    required=False,
  )

  class Meta:
    model = Questionnaire
    exclude = ['user']
    widgets = {
      'how_about_handson':  forms.Textarea(attrs={'class': 'form-control'}),
      'difficult_other':    forms.Textarea(attrs={'class': 'form-control'}),
      'time_settings':      forms.Select(attrs={'class': 'form-control'}),
      'handson_level':      forms.Select(attrs={'class': 'form-control'}),
      'handson_interest':   forms.Select(attrs={'class': 'form-control'}),
      'handson_quantity':   forms.Select(attrs={'class': 'form-control'}),
      'free_opinions':      forms.Textarea(attrs={'class': 'form-control'}),
      'interest_trainings': forms.Textarea(attrs={'class': 'form-control'}),
    }

    
class LoginForm(forms.Form):
  username = forms.CharField(label='Username', required=True, widget=forms.TextInput)
  password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)

  def clean_username(self):
    username = self.cleaned_data['username']
    if username and not User.objects.filter(username=username).exists():
      raise forms.ValidationError('Username is wrong')
    return username

  def clean_password(self):
    password = self.cleaned_data['password']
    if not password:
      raise forms.ValidatonError('Password is wrong')
    if 'username' not in self.cleaned_data:
      return password
    username = self.cleaned_data['username']
    user = User.objects.filter(username=username).first()
    if not user.check_password(password):
      raise forms.ValidationError('Password is wrong')
    return password

survey/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import LoginForm, QuestionnaireForm
from .models import Questionnaire


#class IndexView(generic.base.TemplateView):
#  template_name = 'survey/index.html'
def index_view(request):
  user = request.user
  responded = False
  if user and user.is_authenticated():
    responded = Questionnaire.objects.filter(user=user).exists()

  context = { 'responded': responded }
  return render(request, 'survey/index.html', context)


@login_required(login_url=reverse_lazy('survey:login'))
def edit_view(request):
  user = request.user
  
  if not request.method == 'POST':
    if Questionnaire.objects.filter(user=user).exists():
      q = Questionnaire.objects.get(user=user)
      form = QuestionnaireForm(instance=q)
    else:
      form = QuestionnaireForm()
    context = { 'form': form }
    return render(request, 'survey/edit.html', context)

  q, created = Questionnaire.objects.get_or_create(user=user)
  form =  QuestionnaireForm(request.POST, instance=q)
  if form.is_valid():
    #q = form.save(commit=False)
    #q.user = request.user
    q.save()
    return HttpResponseRedirect(reverse('survey:index'))
  else:
    context = { 'form': form }
    return render(request, 'survey/edit.html', context)

  

def login_view(request):
  if not request.method == 'POST':
    form = LoginForm()
    context = {'form': form}
    return render(request, 'survey/login.html', context)

  form = LoginForm(request.POST)
  if not form.is_valid():
    context = { 'form': form }
    return render(request, 'survey/login.html', context)
  username = form.cleaned_data['username']
  password = form.cleaned_data['password']
  user = authenticate(username=username, password=password)
  login(request, user)
  return HttpResponseRedirect(reverse('survey:index'))


@login_required(login_url=reverse_lazy('survey:login'))
def logout_view(require):
  logout(require)
  return HttpResponseRedirect(reverse('survey:index'))

survey/templates/survey/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>ハンズオン アンケート {% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
  <link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'survey/base.css' %}">
  {% block head %}{% endblock %}
</head>
<body>
<header>
  <div class="page-header">
    <h1>ハンズオン アンケート</h1>
  {% block header %}
    <p>アンケートの回答をお願いします。</p>
  {% endblock %}
  </div>
</header>
<main>
{% block main %}
{% endblock %}
</main>
</body>
</html>

survey/templates/survey/edit.html
{% extends 'survey/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit{% endblock %}

{% block main %}
<div class="container">
{% for field in form  %}
  {% if field.errors %}
<div class="alert alert-danger">
  {{ form.errors }}
</div>
  {% endif %}
{% endfor %}
<form action="{% url 'survey:edit' %}" method="POST">
  {% csrf_token %}
  <p>1. 本日の「Webアプリケーションを作ってみよう！」を受講して、どんな学びを得ましたか？</p>
  <div class="form-group">
    <label for="{{ form.how_about_handson.id_for_label }}">・今日得た学びについて、自由に記載してください。</label>
    {{ form.how_about_handson }}
  </div>
  <div class="form-group">
    <label for="{{ form.difficult_points.id_for_label }}">・わかりにくいと感じた項はどれですか？（複数回答可）</label>
    {{ form.difficult_points}}
  </div>
  <div class="form-group">
    <label for="{{ form.difficult_other.id_for_label }}">・その他を選択された方は具体的に記載してください</label>
    {{ form.difficult_other }}
  </div>
  <p>2. 本日の「Webアプリケーションを作ってみよう！」の運営についてお聞かせください。</p>
  <div class="form-group">
    <label for="{{ form.time_settings.id_for_label }}">・時間の設定</label>
    {{ form.time_settings }}
  </div>
  <div class="form-group">
    <label for="{{ form.handson_level.id_for_label }}">・内容のレベル感</label>
    {{ form.handson_level }}
  </div>
  <div class="form-group">
    <label for="{{ form.handson_interest.id_for_label }}">・内容はご自身の興味関心に沿っていましたか？</label>
    {{ form.handson_interest }}
  </div>
  <div class="form-group">
    <label for="{{ form.handson_quantity.id_for_label }}">・内容の分量</label>
    {{ form.handson_quantity }}
  </div>
  <div class="form-group">
    <label for="{{ form.free_opinions.id_for_label }}">・運営へのご意見を自由にお書きください</label>
    {{ form.free_opinions }}
  </div>
  <div class="form-group">
    <label for="{{ form.interest_trainings.id_for_label }}">3. 今後受けてみたい研修がありましたら、自由にお書きください。</label>
    {{ form.interest_trainings }}
  </div>
  <p>お疲れ様でした!</p>
  <button type="submit" class="btn btn-primary">回答</button>
</form>
</div>
{% endblock %}

survey/templates/survey/index.html
{% extends 'survey/base.html' %}

{% block title %}Home{% endblock %}

{% block main %}
<div class="container">
{% if user.is_authenticated %}
  <h2>こんにちは{{ user.first_name }}さん</h2>
  {% if responded %}
  <p>アンケート回答ありがとうございました。</p>
  <a href="{% url 'survey:edit' %}"><button>アンケート編集</button></a>
  {% else %}
  <p>アンケート回答をお願いします。</p>
  <a href="{% url 'survey:edit' %}"><button>アンケート回答</button></a>
  {% endif %}
{% else %}
  <p>ログインしてアンケート回答をお願いします。</p>
  <a href="{% url 'survey:login' %}"><button>ログイン</button></a>
{% endif %}
</div>
{% endblock %}

survey/templates/survey/login.html
{% extends 'survey/base.html' %}

{% block title %}Login{% endblock %}

{% block header %}<h3>ログインページ<h3>{% endblock%}

{% block main %}
<div class="container">
  <form action="#" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ログイン">
  </form>
</div>
{% endblock %}